'use strict';
const key=s=>String(s||'').normalize('NFKC').toLowerCase().replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-96)).replace(/[^\p{L}\p{N}]/gu,'');
let records=[],hits=[],page=0;
const $=id=>document.getElementById(id);
const corrections=new Map(Object.entries(window.VTUBER_READINGS||{}).map(([name,value])=>[key(name),value]));
function mergeData(base,extra){const map=new Map(base.map(r=>[r.source_id,{...r}]));for(const r of extra||[]){const old=map.get(r.source_id);map.set(r.source_id,old?{...old,...r,aliases:[...new Set([...(old.aliases||[]),...(r.aliases||[])])]}:r)}return [...map.values()]}
function load(data){records=data.map(original=>{const correction=corrections.get(key(original.display_name));const r={...original,...correction,corrected:!!correction};const sourcedReading=!!r.reading_source&&['manual','official','profile_explicit','directory_explicit'].includes(r.reading_source_kind);r.reading=sourcedReading?r.reading:'';r.romanized_name=r.romanized_source?r.romanized_name:'';return {...r,keys:[r.display_name,r.reading,r.romanized_name,...(r.aliases||[])].map(key)};});$('count').textContent=`収録 ${records.length.toLocaleString()} 件`;}
function find(q){const k=key(q);if(!k)return [];return records.map(r=>{let type=r.keys[0]===k?0:r.keys.slice(1).includes(k)?1:r.keys.some(v=>v&&v.includes(k))?2:9;return{r,type};}).filter(x=>x.type<9).sort((a,b)=>a.type-b.type||a.r.display_name.localeCompare(b.r.display_name,'ja'));}
function render(){const box=$('results');box.replaceChildren();for(const {r,type} of hits.slice(page*30,page*30+30)){const article=document.createElement('article');article.className='result';const badge=document.createElement('span');badge.className='badge'+(type===0?' exact':'');badge.textContent=['表示名が一致','読み・英字が一致','名前の一部が一致'][type];const category=document.createElement(r.category==='AIVTuber'?'a':'span');category.className='category'+(r.category==='AIVTuber'?' ai':'');category.textContent=r.category==='AIVTuber'?'AIVTuber':'VTuber';if(r.category==='AIVTuber'&&/^https:\/\//.test(r.category_source||'')){category.href=r.category_source;category.target='_blank';category.rel='noopener noreferrer';}const name=document.createElement('div');name.className='name';name.textContent=r.display_name;const fields=document.createElement('dl');fields.className='fields';for(const [label,value] of [['読み',r.reading],['英字',r.romanized_name],...(r.aliases?.length?[['別名',r.aliases.join(' / ')]]:[])]){const dt=document.createElement('dt');dt.textContent=label;const dd=document.createElement('dd');dd.textContent=value||'不明';fields.append(dt,dd)}const note=document.createElement('p');note.className='note';note.textContent=r.reading?'出典のある読み':'読みを確認できる情報がありません';if(r.reading&&/^https:\/\//.test(r.reading_source)){const source=document.createElement('a');source.textContent='読みの出典';source.href=r.reading_source;source.target='_blank';source.rel='noopener noreferrer';note.append(document.createTextNode(' · '),source);}article.append(badge,category,name,fields,note);box.append(article)}$('pages').hidden=hits.length<=30;$('page').textContent=`${page+1} / ${Math.max(1,Math.ceil(hits.length/30))}`;$('prev').disabled=page===0;$('next').disabled=(page+1)*30>=hits.length;translateUI();}
function search(){const q=$('query').value;if(!key(q)){$('status').textContent='文字を含む名前を入力してください。';hits=[];page=0;$('status').dataset.state='';render();return}hits=find(q);page=0;const exact=hits.filter(x=>x.type===0).length;$('status').dataset.state=exact?'exact':hits.length?'candidates':'none';$('status').textContent=exact?`同じ表示名が ${exact} 件あります。下の結果を確認してください。`:hits.length?`読み・英字、または名前の一部が一致する候補が ${hits.length.toLocaleString()} 件あります。`:'この辞書では一致する名前が見つかりませんでした。未使用を保証する結果ではありません。';render();}
$('form').addEventListener('submit',e=>{e.preventDefault();search()});document.querySelectorAll('[data-query]').forEach(b=>b.onclick=()=>{$('query').value=b.dataset.query;search()});$('prev').onclick=()=>{page--;render()};$('next').onclick=()=>{page++;render()};
try{load(mergeData(window.VTUBER_DATA,window.VTUBER_EXTRA))}catch(e){$('status').textContent='辞書を読み込めませんでした。ページを再読み込みしてください。'}

$('language').onchange=e=>setLanguage(e.target.value);translateUI();
