'use strict';
const key=s=>String(s||'').normalize('NFKC').toLowerCase().replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-96)).replace(/[^\p{L}\p{N}]/gu,'');
let records=[],hits=[],page=0;
const $=id=>document.getElementById(id);
function load(data){records=data.map(r=>({...r,keys:[r.display_name,r.reading,r.romanized_name].map(key)}));$('count').textContent=`収録 ${records.length.toLocaleString()} 件 · 読み・英字でも検索できます`;}
function find(q){const k=key(q);if(!k)return [];return records.map(r=>{let type=r.keys[0]===k?0:r.keys.slice(1).includes(k)?1:r.keys.some(v=>v&&v.includes(k))?2:9;return{r,type};}).filter(x=>x.type<9).sort((a,b)=>a.type-b.type||a.r.display_name.localeCompare(b.r.display_name,'ja'));}
function render(){const box=$('results');box.replaceChildren();for(const {r,type} of hits.slice(page*30,page*30+30)){const article=document.createElement('article');article.className='result';for(const [cls,txt] of [['badge',['表示名が一致','参考の読み・英字が一致','名前の一部が一致'][type]],['name',r.display_name],['reference',`読み（参考）：${r.reading||'不明'} ／ 英字（参考）：${r.romanized_name||'不明'}`],['reference',`登録ID：${r.source_id}`]]){const el=document.createElement('div');el.className=cls;el.textContent=txt;article.append(el)}box.append(article)}$('pages').hidden=hits.length<=30;$('page').textContent=`${page+1} / ${Math.max(1,Math.ceil(hits.length/30))}`;$('prev').disabled=page===0;$('next').disabled=(page+1)*30>=hits.length;}
function search(){const q=$('query').value;if(!key(q)){$('status').textContent='文字を含む名前を入力してください。';hits=[];render();return}hits=find(q);page=0;const exact=hits.filter(x=>x.type===0).length;$('status').textContent=exact?`同じ表示名が ${exact} 件あります。下の結果を確認してください。`:hits.length?`読み・英字、または名前の一部が一致する候補が ${hits.length.toLocaleString()} 件あります。`:'この辞書では一致する名前が見つかりませんでした。未使用を保証する結果ではありません。';render();}
$('form').addEventListener('submit',e=>{e.preventDefault();search()});document.querySelectorAll('[data-query]').forEach(b=>b.onclick=()=>{$('query').value=b.dataset.query;search()});$('prev').onclick=()=>{page--;render()};$('next').onclick=()=>{page++;render()};
function parseCSV(text){const rows=[];let row=[],v='',quoted=false;text=text.replace(/^\uFEFF/,'');for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){v+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(v);v=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(v);if(row.some(Boolean))rows.push(row);row=[];v=''}else v+=c}if(quoted)throw Error('CSVの引用符が閉じられていません。');if(v||row.length){row.push(v);rows.push(row)}const header=rows.shift()||[];const fields=['source_id','display_name','reading','romanized_name'];if(!fields.every(f=>header.includes(f)))throw Error('対応する辞書CSVを選んでください。必要な列：'+fields.join(', '));return rows.map(row=>Object.fromEntries(fields.map(f=>[f,row[header.indexOf(f)]||'']))).filter(r=>r.display_name);}
$('csv').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>100*1024*1024)throw Error('このローカル版で読み込めるCSVは100MBまでです。');const rows=parseCSV(await file.text());if(!rows.length)throw Error('名前が登録されていません。');load(rows);$('error').textContent='';$('status').textContent=`辞書を ${rows.length.toLocaleString()} 件に更新しました。`;hits=[];page=0;render();if(key($('query').value))search()}catch(err){$('error').textContent=err.message}};
try{load(window.VTUBER_DATA)}catch(e){$('status').textContent='辞書を読み込めませんでした。ZIPをすべて展開してから、index.htmlを開いてください。'}
